### PR TITLE
Readme game instructions

### PR DESCRIPTION
**Pull request by smy5152**
### **MILESTONE 4**

- Branch name: readme_game_instructions
- Added a full description of game rules in the README file
- Added Screenshots - demonstrating gameplay stages & _**WIN**_ Scenario
- User is welcomed with a banner and a message stating: Make a choice to place your marker indicating the start of a game

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @smy5152 and @george-swift  :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still a little more to be done before this milestone can be approved.

## REQUIRED

* [x] README file explains rules of the game. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone4/readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

### Make the requested change and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by smy5152** [comment]
> # Status: Changes Required ♻️
> ## Hi @smy5152 and @george-swift 👋
> You've done well so far 👍 and I commend you for that 👏
> However, there are still a little more to be done before this milestone can be approved.
> 
> ## REQUIRED
> * [x]  README file explains rules of the game. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone4/readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
> 
> ### Make the requested change and submit for another review.
> ## Happy Coding 💻
> _Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
> **Elijah O. Ayandokun**
> [Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

NOTED: 
We had called the description and steps - USAGE by mistake. Its updated now.

Thanks & Regards

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Required changes:full_moon:
**Hi team!
Excellent work you have done in this milestone:clap::clap:. The readme looks very professional. However, we just need to make one change to get it approved:muscle:.**

**Mandatory requirement**

- [x] README file explicitly tells how to start the game. ( [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone4/readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)). I get errors when I run ./main.rb when inside or outside the bin directory. Prefixing it with ruby works.

Make the above change and request for another review when you are ready.
Kindly drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy Coding:blush:
Eric Enaburekhan

**Review by arslanbisharat — APPROVED** [review]
# Approved :clap:

Thank you for the changes requested by previous TSEs. Your project is approved now. 

Best,
Arslan Bisharat

**Comment by smy5152** [comment]
Thanks a lot. Appreciate all TSE replies and reviews.

Micronauts: @smy5152  @george-swift

**Pull request merged**
