### PR TITLE
Game Setup -tictactoe

### PR DESCRIPTION
**Pull request by smy5152**
Milestone 1: Setup

The main.rb - can be run from the terminal
Player Names prompted and displayed welcome message.

### CODE REVIEW

**Review by kapkev — CHANGES_REQUESTED** [review]
# [STATUS] CHANGES REQUESTED ♻

Hey, nice project so far. I noticed that you are missing some key features of this project, so we have to improve a few things before moving on:

 - [x] Your project has linter errors, please fix it;

### As always, I wish you all the very best and see you at the top🚀

#### 👨🏻‍💻 TSE: Kevin Alves

📫 Have any question? Reach out through slack;

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

### Hi Team, your `main.rb` is executable, good job on that 👍 

Kindly update this and we will be done with this milestone.

- [x]  You should have a `lib` directory (with `.gitkeep` file OR any other empty file(s)). ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)).  Having the `.gitkeep` file inside the `lib` directory will allow you to be able to push the empty directory to your repo.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED!! :recycle: :red_circle: 
-----------
Hello team!! :wave: Excellent job working on this milestone :clap: 
There is one thing to work on to fulfill this milestone :hammer_and_wrench: See it below :point_down: 
---------

- [x] Your .rubocop.yml is incomplete. Please copy the file from [Here](https://github.com/microverseinc/linters-config/blob/master/ruby/.rubocop.yml) Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students.
--------------
Make the required change :point_up_2:  and send it for another review :muscle: 
HAPPY CODING!!

AngelicConcreteHypsilophodon-max-1mb

**Review by acushlakoncept — APPROVED** [review]
# Status: PROJECT APPROVED  🎉 🚀

### Well done on implementing all the requested changes. 👏 👏 👏 

I will go ahead and mark this as complete, feel free to merge when you are ready. All the best with the next milestone.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Comment by smy5152** [comment]
### **MILESTONE: 2**
Branch name: user_interface
main.rb file is responsible for user interaction.
Added user input steps & what to display back.
Prompt User for input.
Moves displayed on Board.
Mock Gameplay works.

**Comment by kapkev** [comment]
# INVALID PULL REQUEST ⚠

You should have merged this PR right here: 
> 
> # Status: PROJECT APPROVED 🎉 🚀
> ### Well done on implementing all the requested changes. 👏 👏 👏
> 
> I will go ahead and mark this as complete, feel free to merge when you are ready. All the best with the next milestone.
> ### Cheers and Happy coding! 💻 👏
> 
> (Feel free to contact me on slack(@acushla), if you have any additional question)
> Uduak Essien
> [Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

and then open a new one. That's how Pull Requests works. Once they're approved, you merge the changes.

**Comment by smy5152** [comment]
MERGED: After reverting to the commit status after APPROVED.

**Pull request merged**
