### PR TITLE
Add test framework

### PR DESCRIPTION
**Pull request by smy5152**
The Test methods created below are useful to test the functionality of all the methods used to make the gameplay work smoothly. You can run the same as we have mentioned in the readme file.

### CODE REVIEW

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯
  - [x] It has a descriptive branch name 💯

- ### To Improve
  - [x] [MANDATORY] pull-request description should be about what you have done not project requirements.
  - [x] [MANDATORY] tests are failing, kindly fix them.
  Capture6

  


_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on @slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
@slack: Rukundo Eric**

**Comment by smy5152** [comment]
Thanks for the reply & review - sorry about the failed test.

Rubocop - does the auto-correct ` :player -> player `

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Sunil Devalla & Smymisr Yamani** 
Good job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
Just a few details to improve before you can go ahead:

- [x] Fix all rubocop offenses:



- [x] Add a screenshot in your README file
- [x] Test both positive and negative scenarios for each public method. You might use "to_not eql" and "to_not be_an".
- [x] In your test files, replace "require" with "require_relative"
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by SunilDevalla** [comment]
Thanks for the timely review, we will change the suggestions and request another review...

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by smy5152** [comment]
@umairarshadbutt Thank you.

Appreciate it and Thanks to all CRs.

**Pull request merged**
